### ISSUE TITLE
[Feature request] Improved Svelte support

### ISSUE THREAD

**Issue by mjholub** [neanias/everforest-nvim#17]
I really like that this colorscheme is capable of highlighting  `<style>` blocks in Svelte, but in `<script>` section, comments or literals are not handled too well. See screenshot. 
![image](https://github.com/neanias/everforest-nvim/assets/86662980/26b3254d-cc3e-48a9-8612-bb1473646e64)

**Comment by neanias** [comment]
Hi! What would you like the comments to look like? The treesitter parser for Svelte tags those comments as `@comment.javascript`, so it'll be using the `@comment` styles

**Comment by neanias** [comment]
That's what I'm saying: it's already the same as JS as far as I can tell. Does this same snippet look different if you put it in a JS file (e.g. `foo.js`)?

**Comment by mjholub** [comment]
see here
![image](https://github.com/neanias/everforest-nvim/assets/86662980/a8bbade3-c5cd-4b7e-bbaa-4a2c9fbb0a8d)

**Comment by mjholub** [comment]
OK I tried with other colorschemes and the issue persists. Using `:set ft=html` seems to mostly resolve the issue. I'll open an issue at tree-sitter-svelte.
