### ISSUE TITLE
Go Packages and colors

### ISSUE THREAD

**Issue by NicolasGB** [neanias/everforest-nvim#18]
First of all thank you for the plugin. Since finding it i've not switched coloscheme, it is soo good so congratulations.

I'm opening this issue because since the latest updates to match the new treesitter tags (or so it seems with your latest commits) the packages in golang have the same color as the types and it's a bit annoying, previously packages were white.  
![image](https://github.com/neanias/everforest-nvim/assets/17547539/abd900e3-40fa-4368-82eb-e1873f7f0ae4)

Would it be possible to set it up with a different color? is this change intented or it's a bug? If it's intented would you help me override it in my config? i've tried overriding it with the "on_highlights" config in the setup but i couldn't make it work.

Again thanks for the theme and the maintainance!

**Comment by NicolasGB** [comment]
Sure! here you go, the TS value seems to be @module.go

![image](https://github.com/neanias/everforest-nvim/assets/17547539/bc3280c3-6b3b-461c-a442-bba3226d0718)

**Comment by neanias** [comment]
Thanks, I'll look into it

**Comment by neanias** [comment]
Just pushed a commit that should have fixed it. Would you update and test, please?

**Comment by NicolasGB** [comment]
Yes it's back to the old behavior, thanks!
![image](https://github.com/neanias/everforest-nvim/assets/17547539/f3a44150-ce04-47a5-9040-8c185a96e8f7)

**Comment by neanias** [comment]
No problem
