### ISSUE TITLE
Feat Request: Variable Transparency

### ISSUE THREAD

**Issue by GianniBYoung** [neanias/everforest-nvim#20]
I would like to be able to have a slightly transparent background instead of all or nothing. Is this something that can be reasonably added to the plugin?

**Comment by neanias** [comment]
Hi there! I've done some research and it seems like it's not currently possible in Neovim, but may be possible through your terminal. Transparency in Neovim is set by having no background colour and then, as I understand it, the transparency of the terminal you use will take over. Colours in Neo/vim don't allow for opacity gradients, alas.

**Comment by GianniBYoung** [comment]
Gotcha, I was able to make the adjustment in my terminal config, thanks!
