### ISSUE TITLE
how to change currentword highlight

### ISSUE THREAD

**Issue by Leiyi548** [neanias/everforest-nvim#21]
Hello,I like you colorscheme,but i have some issuse how to change the currentword highlight.
Default is bold,I want tokyonight style.
![image](https://github.com/neanias/everforest-nvim/assets/76139422/d136bd81-468b-498a-901e-8ddb7c0ee1e3)
![image](https://github.com/neanias/everforest-nvim/assets/76139422/33705496-f751-403f-8832-5fa5464bb5d8)

**Comment by Leiyi548** [comment]
> Hi, to clarify, would you just like it unstyled/no different to the underlying highlight?

I want style like tokyonight

**Comment by neanias** [comment]
Ok, I think this would be similar to tokyonight:

```lua
require("everforest").setup({
  on_highlights = function(hl, palette)
    hl.CurrentWord = { fg = palette.none, bg = palette.bg_dim }
  end,
})
```

**Comment by Leiyi548** [comment]
> Ok, I think this would be similar to tokyonight:
> 
> ```lua
> require("everforest").setup({
>   on_highlights = function(hl, palette)
>     hl.CurrentWord = { fg = palette.none, bg = palette.bg_dim }
>   end,
> })
> ```
Perfect!
