### ISSUE TITLE
Blankline support seemingly broken? 

### ISSUE THREAD

**Issue by igniscyan** [neanias/everforest-nvim#26]
![image](https://github.com/user-attachments/assets/31017dec-30cd-4e2b-a229-84e750608617)
I could be totally wrong, but is this above the intended result of using this theme in combination with indent-blankline? This seems broken, but I'm unsure if it's my personal configuration.

**Comment by neanias** [comment]
Sorry, unclear what you're expecting to see here vs what you've got in the screenshot?

**Comment by neanias** [comment]
Oh, right, this is the intended. What are you seeing instead?

**Comment by igniscyan** [comment]
> Oh, right, this is the intended. What are you seeing instead?

I may be wrong, typically aren't the indent lines supposed to be unemphasized until you're in scope? In the screenshot all are emphasized

**Comment by neanias** [comment]
What happens if your cursor is on a line inside the scope?

**Comment by igniscyan** [comment]
> What happens if your cursor is on a line inside the scope?

I'm embarrassed and annoyed, lol.

Turns out Windows term has a setting to make characters it deems "difficult" more legible... and it turns out I had enabled that at some point. Since disabling things working flawlessly :) Sorry for the needless issue.

**Comment by neanias** [comment]
No worries! Glad you worked it out
