### ISSUE TITLE
Transparent background does not work in terminal

### ISSUE THREAD

**Issue by Tekitori19** [neanias/everforest-nvim#27]
Hi there,

I use Lazyvim and transparent background (it's work well) but my terminal in lazyvim doesn't transparent.

My config:
```

  {
    "neanias/everforest-nvim",
    config = function()
      require("everforest").setup({
       transparent_background_level = 1,
        diagnostic_virtual_text = "coloured",
        disable_terminal_colours = true,
        background = "soft",
        ui_contrast = "low",
      })
    end,
  },
```

My issues:
![image](https://github.com/user-attachments/assets/8dc29d4b-2c93-445b-b457-50bd34107d47)

Thank you so much ^-^

**Comment by neanias** [comment]
Hmm, that's interesting. Do you use a plugin for opening your terminal? What happens if you use `:terminal` without using the plugin?

**Comment by Tekitori19** [comment]
It works fine on `:terminal`, but it can't be transparent on `<C-/>` (keymaps to turn on terminal in lazyvim) and also mason doesn't transparent too.

`:terminal`:
![image](https://github.com/user-attachments/assets/bb73f0ac-1b0d-4ff6-98c7-e2868ac82d4e)

`<C-/> and mason`:
![image](https://github.com/user-attachments/assets/74acd1cd-1751-4fe5-8968-8dbf6ada3eb8)
![image](https://github.com/user-attachments/assets/7f2f03d0-48b6-48be-9e8e-133060791252)

**Comment by Tekitori19** [comment]
Thank you so much sir, your code fixed my issues. Have a nice day sir.
