### ISSUE TITLE
Highlighting Issue with Git and Diagnostics When Using barbar.nvim

### ISSUE THREAD

**Issue by okm321** [neanias/everforest-nvim#28]
I am experiencing an issue when using the Everforest colorscheme with the barbar plugin in Neovim. Specifically, when displaying Git and diagnostic information on the buffer line, unwanted highlighting appears.
![CleanShot 2024-09-01 at 16 36 14@2x](https://github.com/user-attachments/assets/b5a5b590-ac7a-41d7-a47f-2e6de80268b7)

After some investigation, I discovered that the background color for the affected areas is tied to palette.statusline1. I attempted to override this with the following code:

```lua
colours_override = function(palette)
  palette.statusline1 = palette.none
end
```
![CleanShot 2024-09-01 at 16 53 13@2x](https://github.com/user-attachments/assets/fa39bace-33c8-4a3b-9b71-ce80528befff)

While this successfully removes the unwanted highlighting, it also affects the status line in lualine, setting it to none, which is not the desired outcome.

Would you have any suggestions on how to resolve this issue without impacting the lualine status line? Any guidance or advice would be greatly appreciated.

**Comment by neanias** [comment]
Fixed by #29
