### ISSUE TITLE
spell_foreground does not work

### ISSUE THREAD

**Issue by Barmaley0** [neanias/everforest-nvim#33]
Tell me what could be the problem? When disabling the function:
spell_foreground = true,
![image](https://github.com/user-attachments/assets/efd655a5-c429-4a0c-80e3-957709643649)
it still colors
![image](https://github.com/user-attachments/assets/61462d9e-b755-45ee-a80b-1582837ce6d6)

**Comment by neanias** [comment]
Hi there, so you've set `spell_foreground = false` in this example? If so, it looks like this warning & error may be related to linting/LSP errors rather than spelling mistakes?

**Comment by Barmaley0** [comment]
Thank you. Shouldn't you set up linting?

**Comment by neanias** [comment]
I mean, the errors & warnings you're seeing here may be coming from your linter, not from the colorscheme spelling colours
