### ISSUE TITLE
May I ask how to set up the ability to switch to the corresponding LuaLineTheme every time when switching between multiple color schemes

### ISSUE THREAD

**Issue by reimu1234** [neanias/everforest-nvim#35]
I really like this color scheme. How can I switch LuaLineTheme automatically when switching color schemes? and use dark mode default when switch everforest
I use LunarVim and other color schemes can switch LuaLineTheme normally

**Comment by neanias** [comment]
Hi there, I think you can set `theme = "auto"` in your Lualine config and then it should switch as you change colour schemes. Re using dark mode default, that's dependent on your neovim configuration, so I'm not sure how off the top of my head. Everforest will render the appropriate colours depending on the `background` option enabled in Neovim
