### ISSUE TITLE
italics not working for keywords

### ISSUE THREAD

**Issue by washepupmage** [neanias/everforest-nvim#36]
I set italics=true in my config and lua keywords are not being rendered as italics.  While going through highlights.lua i see that highlights are being overwritten starting line 556 down to 782. Those overwrites do not seem to honor the optional_italics switch.
As a workaround I'm commenting out  highlights.lua 556-782 in my local repo for now, which seems to solve the problem.

**Comment by neanias** [comment]
Hi there! That section of the highlights is Treesitter & LSP semantic token specific for Neovim >0.8. With these colours disabled as you have them, what does `:Inspect` say if you have your cursor over a Lua keyword? It may be a clash between the standard highlights and Treesitter.

**Comment by neanias** [comment]
Otherwise, see this issue in the upstream repo: https://github.com/sainnhe/everforest/issues/128#issuecomment-1793262022

**Comment by washepupmage** [comment]
a few examples:

"local" - @keyword.lua links to Red lua
"if" - @keyword.conditional.lua links to Red lua 
"return" -  @keyword.return.lua links to Red lua 

thanks for the quick followup!

**Comment by washepupmage** [comment]
I find this diff should cover most inconsistencies. I fond however that the problem comes from redefining the styles in the "Predefined highlight groups" section. I understand the rationale behind this approach, but it's inevitable that inconsistencies arise

diff --git a/lua/everforest/highlights.lua b/lua/everforest/highlights.lua
index 8ebeacb..f64d354 100644
--- a/lua/everforest/highlights.lua
+++ b/lua/everforest/highlights.lua
@@ -462,7 +462,7 @@ highlights.generate_syntax = function(palette, options)
     TSCharacter = { link = "Aqua" },
     TSCharacterSpecial = { link = "SpecialChar" },
     TSComment = { link = "Comment" },
-    TSConditional = { link = "Red" },
+    TSConditional = { link = "RedItalic" },
     TSConstBuiltin = { link = "PurpleItalic" },
     TSConstMacro = { link = "PurpleItalic" },
     TSConstant = { link = "Constant" },
@@ -472,18 +472,18 @@ highlights.generate_syntax = function(palette, options)
     TSEnvironment = { link = "Macro" },
     TSEnvironmentName = { link = "Type" },
     TSError = { link = "Error" },
-    TSException = { link = "Red" },
+    TSException = { link = "RedItalic" },
     TSField = { link = "Blue" },
     TSFloat = { link = "Purple" },
     TSFuncBuiltin = { link = "Green" },
     TSFuncMacro = { link = "Green" },
     TSFunction = { link = "Green" },
     TSFunctionCall = { link = "Green" },
-    TSInclude = { link = "Red" },
-    TSKeyword = { link = "Red" },
-    TSKeywordFunction = { link = "Red" },
-    TSKeywordOperator = { link = "Orange" },
-    TSKeywordReturn = { link = "Red" },
+    TSInclude = { link = "RedItalic" },
+    TSKeyword = { link = "RedItalic" },
+    TSKeywordFunction = { link = "RedItalic" },
+    TSKeywordOperator = { link = "OrangeItalic" },
+    TSKeywordReturn = { link = "RedItalic" },
     TSLabel = { link = "Orange" },
     TSLiteral = { link = "String" },
     TSMath = { link = "Blue" },

**Comment by washepupmage** [comment]
not a problem, thanks for clarifying!

**Comment by neanias** [comment]
No problem. Lmk if you want any help with setting up overrides
