### ISSUE TITLE
Git Gutter Different Background

### ISSUE THREAD

**Issue by traviscrist** [neanias/everforest-nvim#5]
With the theme configured as "medium" and with the `transparent_background_level` as 0 the gitgutter and lsp signs seem to have a different background. Am I configuring something wrong? 
![Screenshot 2023-06-13 at 12 12 17 PM](https://github.com/neanias/everforest-nvim/assets/4206970/9dce9ea8-c9b7-460d-9314-1a6eb5772262)

If I make the `transparent_background_level` then it all matches but I'd prefer not to use the transparent background.

**Comment by neanias** [comment]
Which plugins are you using for your git gutter? [vim-gitgutter](https://github.com/airblade/vim-gitgutter) or [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim)

**Comment by neanias** [comment]
This is actually an issue with the signs highlights that the git signs highlights are linked to. I'll look into this

**Comment by neanias** [comment]
This is now fixed by f2ad19907975f8742133a489de4ccf7685bb6a13
