### ISSUE TITLE
Flash.nvim legibility

### ISSUE THREAD

**Issue by bredfield** [neanias/everforest-nvim#6]
<img width="425" alt="image" src="https://github.com/neanias/everforest-nvim/assets/490270/0efd5211-8223-4e73-ac1a-59227689cadf">

👋  

I've been using `Flash.nvim` -- appreciate your adding support for it! Unfortunately the `fg` on top of `purple` (for atl least the `hard` variation of everforest) is not very legible. Would dropping the background change and using `purple` for the text color work, as the rest of the theme is greyed?

**Comment by neanias** [comment]
Oh, yeah, that's quite hard to read! I'll have a fiddle around with some colours and see what I can come up with...
